controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    prefix: "/api/v1"
app_payments_get:
    path: /payments/get
    controller: App\Controller\PaymentsController::getPayments
